nome: Pacote Node.js

sobre:
  liberar:
    tipos: [criado]

empregos:
  construir:
    executado: ubuntu-mais recente
    passos:
      - usa: ações/checkout@v4
      - usa: ações/setup-node@v3
        com:
          versão do nó: 16
      - execute: npm ci
      - execute: teste npm

  publicar-gpr:
    necessidades: construir
    executado: ubuntu-mais recente
    permissões:
      pacotes: escrever
      conteúdo: leia
    passos:
      - usa: ações/checkout@v4
      - usa: ações/setup-node@v3
        com:
          versão do nó: 16
          url de registro: https://npm.pkg.github.com/
      - execute: npm ci
      - executar: npm publicar
        ambiente:
          NODE_AUTH_TOKEN: ${{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}}
